### ISSUE TITLE
The function called "text_parse()" doesn't work success.

### ISSUE THREAD

**Issue by eaglekindoms** [nunuhara/alice-tools#10]
When I finished editing the text, and use the command " alice ain edit -t out2-2.txt -o out22.ain dohnadohna.ain". I found nothing have been changed on the game when I use this ".ain" file. And I redump the "out22.ain" file ,I find it's text is same as the dohnadohna.ain's text. Then I see your source code, find where is the file been written. I find the function which called "text_parse()" on the file "src/ainedit/text.c" maybe work without success, it make nothing have been change on the dohnadohna.ain.
![image](https://user-images.githubusercontent.com/28506937/101119356-1e4dbb80-3626-11eb-9f8a-c1592494a319.png)
I print some log where I said.
![image](https://user-images.githubusercontent.com/28506937/101119378-2c034100-3626-11eb-81f9-730d1655367d.png)
Could you tell me where the function called "text_parse()" be implemented.

**Comment by nunuhara** [comment]
text_parse() is automatically generated from the file src/ainedit/text_parser.y by bison.

Are you removing the ';' at the beginning of the lines that you've changed?

**Comment by eaglekindoms** [comment]
Sorry, I don't remove ';' , I tried it again. It success. Thank you very much.
