### ISSUE TITLE
Loss of data on EX file reencoding

### ISSUE THREAD

**Issue by UserUnknownFactor** [nunuhara/alice-tools#14]
After running:
```cmd
alice ex dump -o "ex_file.x" "HentaiLabyrinthEX.ex"
alice ex build -o "HentaiLabyrinthEX.ex" "ex_file.x" 
```
The game seems to break, specifically in the first map after New Game if I move forward one cell and then backtrace all the way to starting point the game crashes. It seems something is lost during the process of reencoding, as I didn't modify the .x file? 

I tried ` --input-encoding cp932` for the first command and `--output-encoding cp932` for the second too but no changes.

**Comment by nunuhara** [comment]
I've sort of fixed this. As a workaround until I make the next release, you can add quotation marks around any identifiers in the .x file that contain asterisks in them. In Hentai Labyrinth, there's 3:

    *移動不可
    *宝箱
    *スタート地点

If you put quotation marks around them it should build correctly:

    "*移動不可"
    "*宝箱"
    "*スタート地点"
