### ISSUE TITLE
Binary pipe output of alice.exe is wrong on windows?

### ISSUE THREAD

**Issue by UserUnknownFactor** [nunuhara/alice-tools#15]
When I try to write file from Python using exe's binary pipe output, I get `b'\r\n'`s instead of `b'\n'`s:
```python
    with open(f"{unicode_noext}.pactex", 'wb') as fout:
        fout.write(run(["alice", "ex", "build", f"{short_path}"], text=False, capture_output=True).stdout)
```
So I need to use `.stdout.replace(b'\r\n',b'\n')` instead of plain `.stdout` which seems to be a brittle solution in case the original stream contained those.

**Comment by nunuhara** [comment]
This *should* be fixed now.
