### ISSUE TITLE
Suggestion: ignorable white-space in manifest files

### ISSUE THREAD

**Issue by differentrain** [nunuhara/alice-tools#18]
In the current manifest files do not support white-space in the file list.
For example.
Correct content:
```
#ALICECG2
output.afa
0,srcDir,PNG,destDir,QNT
```
Wrong content:
```
#ALICECG2
output.afa
0, srcDir, PNG, destDir, QNT
```
This will shows ERROR: line 2: "` srcDir`" is not a directory.

**Comment by nunuhara** [comment]
Fixed, with the caveat that whitespace in the file name will now cause a syntax error instead.

**Comment by differentrain** [comment]
> Fixed, with the caveat that whitespace in the file name will now cause a syntax error instead.

How about using optional double-quotes(`"`)?
