### ISSUE TITLE
Can't extract text from Rance 5D

### ISSUE THREAD

**Issue by MishaIac** [nunuhara/alice-tools#2]
An error appears when extracting text from the System39.ain file.
![image](https://user-images.githubusercontent.com/47920105/92319642-4a57a180-f023-11ea-8168-72f5a10219bf.png)

Game: Rance 5D English by MangaGamer
https://vndb.org/v2046

Here is a sample file
[System39.ain.zip](https://github.com/nunuhara/alice-tools/files/5179159/System39.ain.zip)

**Comment by nunuhara** [comment]
Rance 5D is a system 3.9 game, which uses a different format of .ain file that is not supported by alice-tools. I may add support for this format in the future but for now it it not possible to edit this file with alice-tools.

For working with system 3.9 games, you can use [xsys35c](https://github.com/kichikuou/xsys35c) or Sys3Decompiler which you can find linked [here](https://alicesoft.fandom.com/wiki/User_blog:RottenBlock/System_Programming_Resources).
