### ISSUE TITLE
Illegal byte sequence when extracting file

### ISSUE THREAD

**Issue by shyaple** [nunuhara/alice-tools#21]
I received "ERROR: iconv: Illegal byte sequence" when trying to extract from Sound.afa files that are from the official Chinese version of Rance10 and DohnaDohna.
Problem should be due to Chinese character file names.

Could any kind soul help? I have almost no experience in coding...

**Comment by nunuhara** [comment]
There is a `--input-encoding` option that you can use to specify the character encoding of the .afa file. E.g.

    alice ar extract --input-encoding=GBK Rance10Sound.afa

You might also need to specify the output encoding as GBK, e.g.

    alice ar extract --input-encoding=GBK --output-encoding=GBK Rance10Sound.afa

**Comment by shyaple** [comment]
Thanks! 
It works like a charm
