### ISSUE TITLE
Support for Translated .ain Files

### ISSUE THREAD

**Issue by mrpyq-ae** [nunuhara/alice-tools#22]
Recently I have been working with a certain officially translated version of a game. I am somewhat sure that the encoding of the translation should be GB2312 or a derivative of it. Nevertheless I cannot seem to get the tools to unpack the .ain file without some iconv error no matter how I configured the encoding. Do you mind taking a look at it? Thanks.
[ain-file.zip](https://github.com/nunuhara/alice-tools/files/6330512/ain-file.zip)

**Comment by nunuhara** [comment]
For some reason one of the function names in this file has some junk (0xFFFFFFFF) prepended to it. I've fixed this by simply skipping over any 0xFF bytes at the beginning of a function name.

I was able to dump and rebuild the file using the GBK encoding after making this change. I haven't tried running the rebuilt file but I don't think there should be any problems.

**Comment by mrpyq-ae** [comment]
I see. Thanks for the help!
