### ISSUE TITLE
exbuild/ainedit: iconv doesn't show what line it was processing when encountered error

### ISSUE THREAD

**Issue by UserUnknownFactor** [nunuhara/alice-tools#3]
In 0.6.0 ainedit shows just generic error that doesn't help with finding where the bugged line(s) located:
```
*ERROR*(../src/tools/conv.c:convert_text:35): iconv: Illegal byte sequence
```
It would be better if the program showed either starting/ending line of the bad data or some understandable context. 
(I don't get why it bugs in the first place though, it opens in text editors without problems.)

**Comment by GigaboyX** [comment]
It might be a character the program doesn't understand after any change. For example when that shows up for me it is due to characters like ♀ because it changes to ♀ instead of what it normally is.

**Comment by UserUnknownFactor** [comment]
I think it would be better if the program would just skipped those lines over or ignored the invalid subsequence at the least, issuing a warning message. If there are over hundred lines with errors, things get messy when you need to fix each one of them blindly without the line numbers to look into.

**Comment by nunuhara** [comment]
It's possible to ignore invalid characters by adding "//IGNORE" to the end of the encoding name with the --input-encoding and --output-encoding options. E.g. "CP932//IGNORE", "UTF-8//IGNORE", etc.
Anyways the file name and line number should now be displayed in the error message. I'll probably release a new version this weekend.
Thanks for the report.
