### ISSUE TITLE
Newby Help

### ISSUE THREAD

**Issue by Bootrfangers** [nunuhara/alice-tools#37]
It feels so awkward to ask this but I have no idea how to get this working. Not too knowledgeable about command prompts.

I would like to use this tool to unpack the DohnaDohnavoice.afa and DohnaDohnaCG.afa. 

Running the alice.exe just quickly opens a cmd but it closes instantly. 
Sorry to be a pain in the ass.

**Comment by nunuhara** [comment]
You'll need to open a command prompt and then use the `cd` command to change directory to the location where `alice.exe` is. From there you will be able to run the commands in the documentation.

For example, if you extracted alice-tools to `C:\alice-tools`, and then copied the .afa files into the same directory, you could run:

    cd C:\alice-tools
    alice ar extract -o voice DohnaDohnaVoice.afa
    alice ar extract -o cg DohnaDohnaCG.afa

This will extract the contents of the two archives to the directories `C:\alice-tools\voice` and `C:\alice-tools\cg`.

**Comment by Bootrfangers** [comment]
Thank you, Thank you!

Turns out having AliceTools on my E drive was not letting me change directories in the command prompt but i figured that out
by changing it to my C drive.

I really appreciate the reply, stay awesome.
