### ISSUE TITLE
i cant extract .ain (its weight is 0kb) 

### ISSUE THREAD

**Issue by faraonjc56** [nunuhara/alice-tools#38]
![ain 1](https://user-images.githubusercontent.com/29671562/173731753-4f0f2e0f-3f0d-4618-a480-5fef19ef32a9.png)
![ain 2](https://user-images.githubusercontent.com/29671562/173731755-bc6b1d01-e700-4ed5-a372-2cdb65683077.png)

I attach the .ain file for you to try
https://drive.google.com/file/d/1YD_kuJpnr88D6yFVawfHVUyuu30RKm9G/view?usp=sharing

**Comment by nunuhara** [comment]
Thanks for the report.
This should be fixed in [version 0.12.0](https://github.com/nunuhara/alice-tools/releases/tag/0.12.0).
