### ISSUE TITLE
aindump: generates unparsable file

### ISSUE THREAD

**Issue by UserUnknownFactor** [nunuhara/alice-tools#4]
When the text should be:
```
;s[N] = "\n"
```
it is written in some case as: 
```
;s[N] = "
\n"
```

**Comment by nunuhara** [comment]
Can you give an example of a game where this issue occurs? I'm unable to reproduce this on any of the ain files I've tried. I suspect I might have fixed this at some point since the last release.

**Comment by UserUnknownFactor** [comment]
Hentai Labyrinth's main AIN does this for example.

**Comment by nunuhara** [comment]
Strange, I am not able to reproduce this with either 0.6.0 or the latest git master. Are you using an output encoding other than the default?

**Comment by UserUnknownFactor** [comment]
It's reproducible on my system though using `aindump -t -o out.txt HentaiLabyrinth.ain`:
```
; backlog::detail::CBackLogView@DebugLogTextToClipboard
;s[1153] = "
\n"
```
**ps:** By the way, please, put the .exe versions in their default output, I am not 100% sure, but the version should be 0.6.0 because I only downloaded `alice-tools-0.6.0bin.zip`

**Comment by nunuhara** [comment]
Should be fixed now. I'll probably release a new version this weekend.
Thanks for the report.
