### ISSUE TITLE
Request: .pcf image format

### ISSUE THREAD

**Issue by Cosetto** [nunuhara/alice-tools#41]
Can you add support for converting pcf files? The format is used in Dohna Dohna English release
[DohnaDohna.zip](https://github.com/nunuhara/alice-tools/files/9981035/DohnaDohna.zip)

**Comment by nunuhara** [comment]
pcf images are now supported as of [version 0.12.0](https://github.com/nunuhara/alice-tools/releases/tag/0.12.0)

**Comment by Cosetto** [comment]
Thank you
