### ISSUE TITLE
noreturn define breaks GUI compilation on macOS

### ISSUE THREAD

**Issue by OPNA2608** [nunuhara/alice-tools#45]
[libsys4 sets a define called `noreturn` in `system4.h`](https://github.com/nunuhara/libsys4/blob/958e1b676243a9b5b9225966e98c62b920ed5569/include/system4.h#L30-L34), which alice-tools [also](https://github.com/nunuhara/alice-tools/blob/2c5aa532ff081dc404184b7d540c202c39473555/include/alice/jaf.h#L449-L451) [uses](https://github.com/nunuhara/alice-tools/blob/4138acf94a54a05a59dacd796861aef4721781a2/src/core/jaf/error.c#L394-L418). This affects both repositories in some way.

When the GUI code is compiled on macOS, an error is caused by the `noreturn` define getting unintentionally resolved.

![Screenshot_macOS_2022-12-30_23:40:24](https://user-images.githubusercontent.com/23431373/210116274-b28a3842-896d-4c5e-9c1c-0226c10d976f.png)

The custom `noreturn` define accidentally gets resolved inside macOS' system headers due to the inclusion of `<assert.h>` after `system4.h`. `alice.h` itself includes `<assert.h>` before `system4.h`. The error appears only in `src/gui/galice.cpp` because there, `system4.h` is manually included before `alice.h`.

The fix may be as simple as including `alice.h` before `system4.h`, but I think the better solution is to rename `noreturn` to something more distinct so such an inclusion order problem does not eventually reappear.

**Comment by nunuhara** [comment]
This should be fixed now. The standard C keyword _Noreturn is used instead.
