### ISSUE TITLE
Some (DCF) CG files from Dohna Dohna don't convert properly

### ISSUE THREAD

**Issue by OPNA2608** [nunuhara/alice-tools#46]
The following are some examples of CG files from Dohna Dohna that look fine when viewed in `galice`, but get broken when extracted via `galice` / converted via `alice`:

- [`ウルンセルΩ／待機／０１.dcf`](https://github.com/nunuhara/alice-tools/files/10329749/default.zip)
This one prints `*WARNING*(../subprojects/libsys4/src/dcf.c:dcf_apply_diff:165): DCF base CG width differs` on the terminal when viewed in `galice`, has broken transparency and looks like a different image in the editor.
- [`イベント／魚の館／２２.dcf`](https://github.com/nunuhara/alice-tools/files/10329750/default.zip)
This one gets turned into a blocky cutout on a black background.

**Comment by nunuhara** [comment]
This should be fixed now in [0.12.1](https://github.com/nunuhara/alice-tools/releases/tag/0.12.1)

**Comment by OPNA2608** [comment]
Checked on 0.12.1, no change. Are they supposed to look like that?

Similar to https://github.com/nunuhara/alice-tools/issues/47#issuecomment-1372421485 I'm trying to guess how the format might work. It looks like there is a base graphic that DCF files are applied on top of, and the DCF has a sort of mask to indicate that only certain "blocks" of it are intended to be applied onto the base? If that's the case, maybe the mask could be exported into a separate black/white texture (it can't be put into the alpha channel because some DCF images also contain transparency)? That would be useful for reconstructing the composition in i.e. GIMP.

**Comment by nunuhara** [comment]
Oops, I forgot to push the change to libsys4 before building the release. I've updated the .zip file for 0.12.1 now so please try it again.

**Comment by OPNA2608** [comment]
The warnings on DCFs have now disappeared and all images display properly in `galice`, but the exports are still weird to look at & hard to use without knowing what the base CG is & which areas are supposed to apply to it. Do you think something could be done about that?

**Comment by nunuhara** [comment]
Ah, the export from the GUI was still broken. I only checked the command line export.
It should be fixed now.

**Comment by OPNA2608** [comment]
Ah yes that seems to have fixed it, many thanks!
