### ISSUE TITLE
Sengoku asd file will dump but won't build

### ISSUE THREAD

**Issue by Sethbarrie** [nunuhara/alice-tools#62]
Hi there, working on editing a save file to move some commanders to an enemy clan for capturing. I was able to dump save files correctly but I'm not able to build them, even without modifying them. Running the build command always fails.

I also downloaded systemx4 but was unable to see any save dump option as well. I also saved while playing sengoku through systemx4 and tried to and build with that file but no luck either.

I noticed this issue saying you can't build and dump asd but it seems like it was referencing Rance X not sengoku. Is this the case still? I can provide asd and json files if needed or helpful.

https://github.com/nunuhara/alice-tools/issues/53#issuecomment-1626333960

Running on powershell with the portable release 0.13, Sengoku is mg version 1.04

Thank you!

**Comment by kichikuou** [comment]
Do you get any error messages when you run the build command?

It would be helpful if you could upload the `.asd` file.

**Comment by Sethbarrie** [comment]
Error message is ERROR: Failed to parse JSON

Sorry for not posting that in the initial response. ASD is here

[Rance7_374.zip](https://github.com/nunuhara/alice-tools/files/14923266/Rance7_374.zip)

**Comment by kichikuou** [comment]
Hmm, it seems to be working fine in my Windows environment.

```
C:\alice-tools-0.13.0>alice asd dump Rance7_374.ASD -o out.json

C:\alice-tools-0.13.0>alice asd build out.json -o out.asd

C:\alice-tools-0.13.0>fc Rance7_374.ASD out.asd
Comparing files Rance7_374.ASD and OUT.ASD
FC: no differences encountered
```

**Comment by Sethbarrie** [comment]
I see my problem, I was initially using > to get the data into the json. Using the built in output works. Thank you for the help with that!
