### ISSUE TITLE
Rance 01 Remake - Issue extracting .ald files

### ISSUE THREAD

**Issue by thempc** [nunuhara/alice-tools#8]
Hi, I downloaded the 0.7 released tools and have been trying to extract the audio from the Rance 01 Remake recently released by MangaGamer, to listen to outside the game.

I'm reasonably sure I followed all instructions, but unfortunately cannot get extraction to work, seems to error each time I try.
I've done bit of research, and afaik this runs on System 4.2, which, I think is supported? I unfortunately don't have much more info except a screenshot of the commandline and the associated errors, see below.

![image](https://user-images.githubusercontent.com/323329/100098768-2dcf4680-2e67-11eb-860e-84c2c788f72e.png)

If there's anything I missed on my end, I apologize, and if so it would be greatly appreciated to hear what it is.
If not and there's no support for this game yet, it would be great to see it added :)

**Comment by nunuhara** [comment]
Thanks for the report. This should be fixed now. I'll make a new release sometime today.
