### ISSUE TITLE
There`s no change in the game

### ISSUE THREAD

**Issue by okskcctv** [nunuhara/alice-tools#9]
I extract .ain file to .txt It is good. I can see all of dialog
I edit and save .txt file that dialog parts and repacking that to .ain
And then move it to game folder to exchange to new .ain file
But there is no change in the game

why???
I think it is because .fnl file

If not I want to know the cause and the solution
OR
If it is and how can I edit .fnl file?

Even if the sentences are strange because I am not good at English, I would like you to look at them.

**Comment by nunuhara** [comment]
The steps you listed sound right. Did you maybe forget to uncomment the lines that you changed? For example,

    ;m[123] = "asdf"

instead of,

    m[123] = "asdf"

Just a guess. The fnl file shouldn't need to be changed, it just contains the fonts used by the game.

**Comment by okskcctv** [comment]
Thank you.
It is applied by removing the;
I made a mistake

**Comment by eaglekindoms** [comment]
When I finished editing the text, and use the command " alice ain edit -t out2-2.txt -o out22.ain dohnadohna.ain". I found nothing have been changed on the game when I use this ".ain" file. And I redump the "out22.ain" file ,I find it's text is same as the dohnadohna.ain's text. Then I see your source code, find where is the file been written. I find the function which called "text_parse()" on the file "src/ainedit/text.c" maybe work without success, it make nothing have been change on the dohnadohna.ain.
![image](https://user-images.githubusercontent.com/28506937/101117784-c1043b00-3622-11eb-8f11-db90abf331e6.png)
I print some log where I said.
![image](https://user-images.githubusercontent.com/28506937/101118527-345a7c80-3624-11eb-8c20-82e8dc9e26c1.png)
Could you tell me where the function called "text_parse()" be  implemented.

**Comment by nunuhara** [comment]
Unfortunately the game engine uses the shift-jis encoding internally, which doesn't support Korean text.
In order to use a different text encoding, you would need to patch dohnadohna.exe. Apparently Chinese fans have figured out how to do this, but I'm not sure how they do it.

**Comment by okskcctv** [comment]
I see. It is enough to find some pictures . Thank you for answer. 
I have been very helpful. Thank you again.
